### PR TITLE
Eclipse theme

### PR DESCRIPTION
**Pull request by AD2076**
Added presets for Eclipse and his editor to match Arc Dark theme

### CODE REVIEW

**Comment by FadeMind** [comment]
@AD2076 You can create proper release for papirus (light) and papirus-dark (dark theme)
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme-kde

Thank you for your work.

**Comment by AD2076** [comment]
Of course I can. Where can I find palettes with proper colours? I need Arc Dark too, used a color picker to theme eclipse...

**Comment by FadeMind** [comment]
@AD2076 

@varlesh  did not published this stuff. 

If you have a time, you can extract pallete from current themes and prepare proper docs about this.

@varlesh made this stuff alone. I am just bug hunter, Makefile coder and temporary admin of all Papirus Suite Project.

Regards

**Comment by AD2076** [comment]
AFAIK papirus dark is discontinued... I am gonna create papirus theme

**Pull request merged**
